// Generated by EXACT-HF/step28_export_calculator_model.py -- do not edit by hand.
window.EXACTHF_MODEL = {
  "name": "EXACT-HF 10-variable bedside model",
  "model": "Elastic-net logistic regression (L1 ratio 0.5, 5-fold CV)",
  "features": [
    "Betablocker_Prescribed",
    "Loop_Diuretic_Prescribed",
    "na",
    "Age",
    "urea",
    "bmi",
    "Statin_Prescribed",
    "mean_blood_presuure",
    "nyha",
    "bp_dias"
  ],
  "meta": {
    "Betablocker_Prescribed": {
      "label": "Beta-blocker at discharge",
      "kind": "binary"
    },
    "Loop_Diuretic_Prescribed": {
      "label": "Loop diuretic at discharge",
      "kind": "binary"
    },
    "Statin_Prescribed": {
      "label": "Statin at discharge",
      "kind": "binary"
    },
    "na": {
      "label": "Serum sodium",
      "unit": "mmol/L",
      "kind": "number",
      "step": 1
    },
    "Age": {
      "label": "Age",
      "unit": "years",
      "kind": "number",
      "step": 1
    },
    "urea": {
      "label": "Serum urea",
      "unit": "mmol/L",
      "kind": "number",
      "step": 0.1
    },
    "bmi": {
      "label": "Body-mass index",
      "unit": "kg/m\u00b2",
      "kind": "number",
      "step": 0.1
    },
    "mean_blood_presuure": {
      "label": "Mean arterial pressure",
      "unit": "mmHg",
      "kind": "number",
      "step": 1
    },
    "bp_dias": {
      "label": "Diastolic blood pressure",
      "unit": "mmHg",
      "kind": "number",
      "step": 1
    },
    "nyha": {
      "label": "NYHA class",
      "kind": "nyha"
    }
  },
  "preprocess": {
    "Betablocker_Prescribed": {
      "median": 1.0,
      "clip_min": 0.0,
      "clip_max": 1.0
    },
    "Loop_Diuretic_Prescribed": {
      "median": 1.0,
      "clip_min": 0.0,
      "clip_max": 1.0
    },
    "na": {
      "median": 138.0,
      "clip_min": 52.552,
      "clip_max": 152.7860000000005
    },
    "Age": {
      "median": 70.0,
      "clip_min": 25.226,
      "clip_max": 101.0
    },
    "urea": {
      "median": 7.9,
      "clip_min": 1.5187,
      "clip_max": 44.650400000000445
    },
    "bmi": {
      "median": 23.5,
      "clip_min": 12.0574,
      "clip_max": 56.7473000000004
    },
    "Statin_Prescribed": {
      "median": 1.0,
      "clip_min": 0.0,
      "clip_max": 1.0
    },
    "mean_blood_presuure": {
      "median": 95.7,
      "clip_min": 58.832,
      "clip_max": 165.95200000000068
    },
    "nyha": {
      "median": 2.0,
      "clip_min": 1.0,
      "clip_max": 4.0
    },
    "bp_dias": {
      "median": 77.0,
      "clip_min": 41.0,
      "clip_max": 148.5600000000004
    }
  },
  "outcomes": {
    "30-day": {
      "coef": {
        "Betablocker_Prescribed": -0.43817587545316494,
        "Loop_Diuretic_Prescribed": -0.5722864799572969,
        "na": -0.1532439886248364,
        "Age": 0.4772969205498038,
        "urea": 0.3473599462800223,
        "bmi": 0.002521680715635274,
        "Statin_Prescribed": -0.3957395330248823,
        "mean_blood_presuure": -0.5524746170080829,
        "nyha": 0.19476181064759712,
        "bp_dias": 0.12878557398068324
      },
      "intercept": -4.412771823763189,
      "scaler_mean": {
        "Betablocker_Prescribed": 0.875426092345832,
        "Loop_Diuretic_Prescribed": 0.892779671521537,
        "na": 137.81293833281686,
        "Age": 69.65940625968392,
        "urea": 9.417970436938333,
        "bmi": 24.25175522156802,
        "Statin_Prescribed": 0.844747443445925,
        "mean_blood_presuure": 96.9355859931825,
        "nyha": 2.0743724821815928,
        "bp_dias": 78.37875426092346
      },
      "scaler_scale": {
        "Betablocker_Prescribed": 0.3302351422637191,
        "Loop_Diuretic_Prescribed": 0.3093931635305368,
        "na": 5.402028409640077,
        "Age": 13.1365560231077,
        "urea": 5.589555802586298,
        "bmi": 5.159620837881725,
        "Statin_Prescribed": 0.3621452750451105,
        "mean_blood_presuure": 16.04755375881469,
        "nyha": 0.408368686705415,
        "bp_dias": 15.21126836927024
      },
      "performance": {
        "test": {
          "n": 807,
          "events": 28,
          "auroc": 0.8154685494223363,
          "auroc_lo": 0.7313634696497341,
          "auroc_hi": 0.8901109481019621,
          "brier": 0.02759474996776649,
          "slope": 0.8600979572523456,
          "intercept": -0.17738185663872374,
          "threshold": 0.011977455976002811
        },
        "external": {
          "n": 5016,
          "events": 235,
          "auroc": 0.862351417623839,
          "auroc_lo": 0.8335683356548751,
          "auroc_hi": 0.8890170533183214,
          "brier": 0.0311358415289531,
          "slope": 0.940997925930099,
          "intercept": -0.04935789159154791,
          "threshold": 0.03526538055773117
        }
      }
    },
    "1-year": {
      "coef": {
        "Betablocker_Prescribed": -0.2195675653822316,
        "Loop_Diuretic_Prescribed": -0.13298851862652686,
        "na": -0.12486726429212561,
        "Age": 0.5240270276059534,
        "urea": 0.3394255676042613,
        "bmi": -0.1376224138552973,
        "Statin_Prescribed": -0.13569017045949844,
        "mean_blood_presuure": -0.42079981589968424,
        "nyha": 0.30868743986062736,
        "bp_dias": 0.12560569906999036
      },
      "intercept": -1.6561737788138917,
      "scaler_mean": {
        "Betablocker_Prescribed": 0.875426092345832,
        "Loop_Diuretic_Prescribed": 0.892779671521537,
        "na": 137.81293833281686,
        "Age": 69.65940625968392,
        "urea": 9.417970436938333,
        "bmi": 24.25175522156802,
        "Statin_Prescribed": 0.844747443445925,
        "mean_blood_presuure": 96.9355859931825,
        "nyha": 2.0743724821815928,
        "bp_dias": 78.37875426092346
      },
      "scaler_scale": {
        "Betablocker_Prescribed": 0.3302351422637191,
        "Loop_Diuretic_Prescribed": 0.3093931635305368,
        "na": 5.402028409640077,
        "Age": 13.1365560231077,
        "urea": 5.589555802586298,
        "bmi": 5.159620837881725,
        "Statin_Prescribed": 0.3621452750451105,
        "mean_blood_presuure": 16.04755375881469,
        "nyha": 0.408368686705415,
        "bp_dias": 15.21126836927024
      },
      "performance": {
        "test": {
          "n": 807,
          "events": 189,
          "auroc": 0.735578157908255,
          "auroc_lo": 0.6933607729319704,
          "auroc_hi": 0.7777527353983664,
          "brier": 0.15591731431713543,
          "slope": 0.9355061893888051,
          "intercept": 0.203523125343277,
          "threshold": 0.20634837673982107
        },
        "external": {
          "n": 5016,
          "events": 1208,
          "auroc": 0.7394405816962547,
          "auroc_lo": 0.723721142792796,
          "auroc_hi": 0.7545928708817964,
          "brier": 0.1553225736592426,
          "slope": 0.9338187264365279,
          "intercept": 0.12889524229302987,
          "threshold": 0.17686523791935677
        }
      }
    }
  },
  "provenance": {
    "development": "3 hospitals (NUH, NHC, CGH), n=4,034; trained on the 3,227-patient train split",
    "external_validation": "5 independent hospitals (KTPH, NTFGH, SGH, TTSH, WHC), n=5,016",
    "note": "Coefficients apply to standardised inputs; see preprocess for median imputation, winsorising bounds and scaler constants."
  }
};
